### ISSUE TITLE
Unlike DLink, other IP cameras do not create date/time based sub folders.  Please consider adding this feature to the gateway for IP cameras that do not do this.

### ISSUE THREAD

**Issue by mazudo** [ms-iot/securitysystem#74]

**Comment by ooeygui** [comment]
Can you provide more details - including specific cameras which do not do this?

**Comment by mazudo** [comment]
Yes.  The Security system the customer used is this one https://www.lorextechnology.com/HD-DVR-Security-system/HD-security-camera-system-with-full-1080p-recording-resolution/prod930002.p#downloadsTab

**Comment by mazudo** [comment]
Won't fix for now.
