### ISSUE TITLE
OneDrive logout button doesn't function

### ISSUE THREAD

**Issue by shawnfoltz** [ms-iot/securitysystem#83]
When signed in & uploading photos to OneDrive, the button to logout of OneDrive does not function. When I click the button the page still says I'm logged in, on both the OneDrive and Home pages

**Comment by mwmckee** [comment]
@mazudo do you have time to take a look at this? If not, I probably can tomorrow.

**Comment by mwmckee** [comment]
@shawnfoltz thanks for the bug report! We'll take a look and follow up here.

**Comment by mazudo** [comment]
Closing as won't fix, since this is no longer urgent for Shawn and we haven't heard complaints from others.
