### ISSUE TITLE
Enabling Windows IoT Remote Server breaks securitysystem app!

### ISSUE THREAD

**Issue by leowise** [ms-iot/securitysystem#84]
Windows IOT OS Version: 10.0.14393.321 
On: Raspberry Pi B
If you enable the Remote Server on the Raspberry device (to use the MS remote client app) then if you attempt to use this app, the app's web server fails with browser error "no_response_error - server did not send any data" is reported on browser (both Edge and Chrome). If you then disable the remote server on the device, then the app works as expected! Question: Why does the use of the Remote Server stops the securitysystem app's web server from responding?

Leowise

**Comment by mazudo** [comment]
Not sure why this happens.  I'll investigate.

**Comment by saraclay** [comment]
Closing this out as this has likely been fixed by new releases since.
